version: '3.9'

services:

  pg-master:
    build: .
    container_name: pg-master
    user: "postgres"
    ports:
      - "5433:5432"
    expose:
      - "5432"
      - "8008"
    command: patroni /postgres0.yml
    depends_on:
      - zoo

  pg-slave:
    build: .
    container_name: pg-slave
    user: "postgres"
    ports:
      - "5434:5432"
    expose:
      - "5432"
      - "8008"
    command: patroni /postgres1.yml
    depends_on:
      - zoo

  zoo:
    image: zookeeper:3.9
    container_name: zoo
    ports:
      - "2181:2181"

  haproxy:
    image: haproxy:3.0
    container_name: postgres_entrypoint
    ports:
      - "15432:5432"
      - "7000:7000"
    depends_on:
      - pg-master
      - pg-slave
      - zoo
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg